name: "Organization Issue Board"
description: "Consolidate issues of an series of repos based on labels"
inputs:
  config-file:
    description: "A JSON file containing an Array of Organizations, Repos, and Labels to query for issues that needs help."
    required: true
  myToken:
    description: "A valid API token scoped to read the repos described in the config-file and commit to the repo where this GHA is used."
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "moon"
  color: "blue"
